server:
  servlet:
    session:
      timeout: 15m

app:
  security:
    username: ${PFS_APP_USER:pfsadmin}
    password: ${PFS_APP_PASSWORD:pfs1234}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hsbc.sel.emgr: INFO
    com.zaxxer.hikari: WARN
    org.springframework.security: WARN
